import type {
  AnalyticsSnapshot,
  CandidateJob,
  TrackedApplication,
} from "@/lib/domain";

const components = (
  requiredSkills: number,
  preferredSkills: number,
  roleSemantics: number,
  experience: number,
  location: number,
  employmentType: number,
  compensation: number,
) => ({
  requiredSkills,
  preferredSkills,
  roleSemantics,
  experience,
  location,
  employmentType,
  compensation,
});

export const demoJobs: CandidateJob[] = [
  {
    id: "demo-product-designer",
    companyId: "almanac",
    company: "Almanac Labs",
    companyInitials: "AL",
    companyColor: "#214f3b",
    title: "Senior Product Designer",
    description:
      "Shape an AI-assisted workspace used by thoughtful, fast-moving teams. You will own complex product areas from research through polished interaction design and partner closely with product and engineering.",
    location: "New York, NY",
    workplaceType: "hybrid",
    employmentType: "full-time",
    salaryMin: 165000,
    salaryMax: 205000,
    currency: "USD",
    applyUrl: "https://boards.greenhouse.io/",
    postedAt: new Date(Date.now() - 2 * 86_400_000).toISOString(),
    isActive: true,
    requiredSkills: [
      "Product design",
      "Figma",
      "User research",
      "Design systems",
    ],
    preferredSkills: ["AI products", "Prototyping"],
    responsibilities: [
      "Lead end-to-end design for a core product area",
      "Turn customer insight into clear product direction",
      "Evolve the shared design system with engineering",
    ],
    benefits: ["Flexible hybrid schedule", "Learning budget", "Equity"],
    score: 92,
    components: components(0.95, 0.8, 0.93, 1, 1, 1, 1),
    matchedSkills: ["Figma", "User research", "Design systems"],
    missingSkills: ["AI product experience"],
    explanation:
      "Your end-to-end product work and design-systems experience line up closely. The strongest gap is direct evidence of shipping an AI feature.",
  },
  {
    id: "demo-product-manager",
    companyId: "northstar",
    company: "Northstar Health",
    companyInitials: "NH",
    companyColor: "#405f92",
    title: "Product Manager, Member Experience",
    description:
      "Own the member journey across discovery, onboarding, and ongoing care. This role combines customer empathy, analytical rigor, and tight cross-functional execution.",
    location: "Remote — United States",
    workplaceType: "remote",
    employmentType: "full-time",
    salaryMin: 145000,
    salaryMax: 185000,
    currency: "USD",
    applyUrl: "https://boards.greenhouse.io/",
    postedAt: new Date(Date.now() - 4 * 86_400_000).toISOString(),
    isActive: true,
    requiredSkills: ["Product strategy", "Analytics", "User research", "Roadmaps"],
    preferredSkills: ["Healthcare", "SQL"],
    responsibilities: [
      "Set strategy and measurable outcomes for member experience",
      "Prioritize and deliver a clear product roadmap",
      "Partner with design, engineering, clinical, and operations teams",
    ],
    benefits: ["Remote-first", "Medical coverage", "401(k) match"],
    score: 87,
    components: components(0.86, 0.6, 0.9, 1, 1, 1, 0.8),
    matchedSkills: ["Product strategy", "Analytics", "User research"],
    missingSkills: ["Healthcare domain"],
    explanation:
      "Your product strategy and customer-discovery background are a strong fit. Healthcare context would improve the match, but it is listed as preferred.",
  },
  {
    id: "demo-frontend-engineer",
    companyId: "beacon",
    company: "Beacon",
    companyInitials: "B",
    companyColor: "#d34a31",
    title: "Frontend Engineer, Growth",
    description:
      "Build fast, elegant experiences that help independent businesses understand and adopt modern financial tools. You will work across experimentation, product foundations, and design quality.",
    location: "San Francisco, CA",
    workplaceType: "hybrid",
    employmentType: "full-time",
    salaryMin: 175000,
    salaryMax: 230000,
    currency: "USD",
    applyUrl: "https://boards.greenhouse.io/",
    postedAt: new Date(Date.now() - 1 * 86_400_000).toISOString(),
    isActive: true,
    requiredSkills: ["TypeScript", "React", "Experimentation", "Accessibility"],
    preferredSkills: ["Next.js", "Fintech"],
    responsibilities: [
      "Ship high-quality growth experiments",
      "Improve shared frontend systems and performance",
      "Partner with product design on accessible interactions",
    ],
    benefits: ["Commuter benefit", "Home office stipend", "Equity"],
    score: 84,
    components: components(0.82, 0.7, 0.88, 0.75, 0.75, 1, 1),
    matchedSkills: ["TypeScript", "React", "Accessibility"],
    missingSkills: ["Experimentation platforms"],
    explanation:
      "Your React and TypeScript depth is highly relevant. Add quantified experimentation outcomes to make the growth connection more explicit.",
  },
  {
    id: "demo-content-strategist",
    companyId: "fieldguide",
    company: "Fieldguide",
    companyInitials: "FG",
    companyColor: "#7e4f8a",
    title: "Content Strategist",
    description:
      "Define the product voice and content systems for a platform that makes complex work feel calm. You will improve onboarding, in-product guidance, and lifecycle education.",
    location: "Remote — United States",
    workplaceType: "remote",
    employmentType: "full-time",
    salaryMin: 120000,
    salaryMax: 155000,
    currency: "USD",
    applyUrl: "https://boards.greenhouse.io/",
    postedAt: new Date(Date.now() - 6 * 86_400_000).toISOString(),
    isActive: true,
    requiredSkills: [
      "Content strategy",
      "UX writing",
      "Information architecture",
    ],
    preferredSkills: ["B2B SaaS", "Research"],
    responsibilities: [
      "Create scalable content standards",
      "Write and test high-impact product journeys",
      "Partner with support and research to identify friction",
    ],
    benefits: ["Remote-first", "Quarterly gatherings", "Wellness benefit"],
    score: 79,
    components: components(0.78, 0.5, 0.82, 0.75, 1, 1, 0.5),
    matchedSkills: ["Content strategy", "User research"],
    missingSkills: ["Information architecture"],
    explanation:
      "The role aligns with your research-led product communication work. Stronger information-architecture examples would close the main required-skill gap.",
  },
  {
    id: "demo-data-analyst",
    companyId: "juniper",
    company: "Juniper Finance",
    companyInitials: "JF",
    companyColor: "#a96d16",
    title: "Senior Data Analyst",
    description:
      "Turn product and customer data into crisp decisions. You will own metrics, build trusted reporting, and work with leaders to identify the most important opportunities.",
    location: "Boston, MA",
    workplaceType: "hybrid",
    employmentType: "full-time",
    salaryMin: 135000,
    salaryMax: 170000,
    currency: "USD",
    applyUrl: "https://boards.greenhouse.io/",
    postedAt: new Date(Date.now() - 7 * 86_400_000).toISOString(),
    isActive: true,
    requiredSkills: ["SQL", "Product analytics", "Data visualization", "Statistics"],
    preferredSkills: ["dbt", "Financial services"],
    responsibilities: [
      "Define and maintain core product metrics",
      "Build decision-ready analyses and dashboards",
      "Mentor partners on analytical methods",
    ],
    benefits: ["Hybrid flexibility", "Professional development", "Equity"],
    score: 74,
    components: components(0.68, 0.5, 0.78, 1, 0.75, 1, 0.8),
    matchedSkills: ["Product analytics", "Data visualization"],
    missingSkills: ["Advanced SQL", "dbt"],
    explanation:
      "Your analytics communication is a strong match, while the résumé needs clearer evidence of advanced SQL and modern transformation tooling.",
  },
  {
    id: "demo-design-program-manager",
    companyId: "lattice",
    company: "LatticeWorks",
    companyInitials: "LW",
    companyColor: "#317168",
    title: "Design Program Manager",
    description:
      "Create the operating rhythm that helps a distributed design organization do its best work. You will improve planning, rituals, and cross-functional visibility.",
    location: "Remote — United States",
    workplaceType: "remote",
    employmentType: "full-time",
    salaryMin: 130000,
    salaryMax: 172000,
    currency: "USD",
    applyUrl: "https://boards.greenhouse.io/",
    postedAt: new Date(Date.now() - 9 * 86_400_000).toISOString(),
    isActive: true,
    requiredSkills: [
      "Program management",
      "Design operations",
      "Stakeholder management",
    ],
    preferredSkills: ["Change management", "Research operations"],
    responsibilities: [
      "Run quarterly and annual design planning",
      "Improve intake and prioritization systems",
      "Create clear operating metrics for design leadership",
    ],
    benefits: ["Remote-first", "Sabbatical program", "Learning budget"],
    score: 71,
    components: components(0.65, 0.5, 0.76, 0.75, 1, 1, 0.8),
    matchedSkills: ["Stakeholder management", "Design systems"],
    missingSkills: ["Formal program management"],
    explanation:
      "Your cross-functional design leadership transfers well, but the résumé should show more explicit ownership of planning systems and operating cadence.",
  },
];

export const demoApplications: TrackedApplication[] = [
  {
    id: "app-almanac",
    job: demoJobs[0],
    status: "interview",
    appliedAt: new Date(Date.now() - 8 * 86_400_000).toISOString(),
    nextActionAt: new Date(Date.now() + 2 * 86_400_000).toISOString(),
    notes: "Portfolio conversation with the design director.",
  },
  {
    id: "app-northstar",
    job: demoJobs[1],
    status: "applied",
    appliedAt: new Date(Date.now() - 3 * 86_400_000).toISOString(),
    nextActionAt: new Date(Date.now() + 4 * 86_400_000).toISOString(),
    notes: "Follow up if there is no response by Monday.",
  },
  {
    id: "app-beacon",
    job: demoJobs[2],
    status: "planned",
    appliedAt: null,
    nextActionAt: new Date(Date.now() + 86_400_000).toISOString(),
    notes: "Tailor impact bullets before submitting.",
  },
];

export const demoAnalytics: AnalyticsSnapshot = {
  viewed: 42,
  interested: 18,
  saved: 7,
  applied: 6,
  interviews: 2,
  swipeRate: 43,
  weeklyActivity: [
    { label: "Mon", value: 2 },
    { label: "Tue", value: 4 },
    { label: "Wed", value: 3 },
    { label: "Thu", value: 7 },
    { label: "Fri", value: 5 },
    { label: "Sat", value: 2 },
    { label: "Sun", value: 4 },
  ],
  statusCounts: [
    { status: "planned", count: 2 },
    { status: "applied", count: 3 },
    { status: "screening", count: 1 },
    { status: "interview", count: 2 },
    { status: "offer", count: 0 },
    { status: "rejected", count: 1 },
    { status: "withdrawn", count: 0 },
    { status: "archived", count: 0 },
  ],
  missingSkills: [
    { skill: "SQL", count: 8 },
    { skill: "AI products", count: 6 },
    { skill: "Experimentation", count: 5 },
    { skill: "Program management", count: 4 },
  ],
  scoreOutcomes: [
    { label: "Interested", value: 86 },
    { label: "Saved", value: 79 },
    { label: "Applied", value: 84 },
    { label: "Rejected", value: 62 },
  ],
  upcomingFollowups: 3,
};
